import { LootItem, Quest } from "./types";

export interface ChestType {
  id: "wooden" | "silver" | "gold" | "diamond";
  name: string;
  cost: number;
  currency: "coins" | "gems";
  minCoins: number;
  maxCoins: number;
  minGems: number;
  maxGems: number;
  itemDropChance: number; // 0-1
  guaranteedRarity?: "common" | "rare" | "epic" | "legendary" | "mythic";
  icon: string;
  color: string;
  bgGradient: string;
}

export const CHESTS: ChestType[] = [
  {
    id: "wooden",
    name: "Wood Chest",
    cost: 100,
    currency: "coins",
    minCoins: 40,
    maxCoins: 120,
    minGems: 1,
    maxGems: 3,
    itemDropChance: 0.5,
    guaranteedRarity: "common",
    icon: "📦",
    color: "#b45309",
    bgGradient: "from-amber-700 to-amber-900",
  },
  {
    id: "silver",
    name: "Knight's Silver Chest",
    cost: 350,
    currency: "coins",
    minCoins: 150,
    maxCoins: 450,
    minGems: 3,
    maxGems: 8,
    itemDropChance: 0.75,
    guaranteedRarity: "rare",
    icon: "🛡️",
    color: "#64748b",
    bgGradient: "from-slate-400 to-slate-700",
  },
  {
    id: "gold",
    name: "Royal Golden Chest",
    cost: 800,
    currency: "coins",
    minCoins: 400,
    maxCoins: 1000,
    minGems: 10,
    maxGems: 25,
    itemDropChance: 0.95,
    guaranteedRarity: "epic",
    icon: "👑",
    color: "#eab308",
    bgGradient: "from-yellow-400 to-amber-600",
  },
  {
    id: "diamond",
    name: "Mythic Crystal Chest",
    cost: 50,
    currency: "gems",
    minCoins: 1200,
    maxCoins: 3000,
    minGems: 25,
    maxGems: 60,
    itemDropChance: 1.0,
    guaranteedRarity: "legendary",
    icon: "💎",
    color: "#06b6d4",
    bgGradient: "from-cyan-400 to-indigo-600",
  },
];

export const ALL_LOOT_ITEMS: LootItem[] = [
  // HATS & HEADGEAR
  {
    id: "hat_crown_gold",
    name: "King of Tables Crown",
    category: "head",
    rarity: "epic",
    cost: 450,
    currency: "coins",
    description: "Forged from pure golden 12x12 times tables.",
    visualTag: "crown_gold",
    glowColor: "#facc15",
    perk: "+5% Coin gain",
  },
  {
    id: "hat_rock_bandana",
    name: "Heavy Metal Rocker Bandana",
    category: "head",
    rarity: "rare",
    cost: 200,
    currency: "coins",
    description: "For true Math Rockstars hitting 120 beats per minute.",
    visualTag: "rock_bandana",
    glowColor: "#ef4444",
  },
  {
    id: "hat_cyber_helm",
    name: "Quantum Cyber Visor",
    category: "head",
    rarity: "legendary",
    cost: 850,
    currency: "coins",
    description: "Calculates answers at the speed of light.",
    visualTag: "cyber_helm",
    glowColor: "#06b6d4",
    perk: "+10% XP gain",
  },
  {
    id: "hat_wizard_hat",
    name: "Archmage Star Hat",
    category: "head",
    rarity: "rare",
    cost: 250,
    currency: "coins",
    description: "Woven with constellations of multiplication spells.",
    visualTag: "wizard_hat",
    glowColor: "#8b5cf6",
  },
  {
    id: "hat_knight_helm",
    name: "Valiant Knight Helm",
    category: "head",
    rarity: "common",
    cost: 80,
    currency: "coins",
    description: "Standard issue for defenders of the Number Realm.",
    visualTag: "knight_helm",
  },

  // EYEWEAR / FACE
  {
    id: "face_neon_shades",
    name: "Neon Rocker Sunglasses",
    category: "face",
    rarity: "rare",
    cost: 180,
    currency: "coins",
    description: "Too cool for slow mental maths.",
    visualTag: "neon_shades",
    glowColor: "#ec4899",
  },
  {
    id: "face_monocle_gold",
    name: "Mathematician's Gold Monocle",
    category: "face",
    rarity: "common",
    cost: 90,
    currency: "coins",
    description: "Inspect every equation with gentlemanly precision.",
    visualTag: "monocle_gold",
  },
  {
    id: "face_flame_eyes",
    name: "Inferno Combo Eyes",
    category: "face",
    rarity: "legendary",
    cost: 40,
    currency: "gems",
    description: "Burns brighter with every streak of correct answers!",
    visualTag: "flame_eyes",
    glowColor: "#f97316",
    perk: "+1 extra combo multiplier",
  },

  // OUTFITS
  {
    id: "outfit_tunic_novice",
    name: "Apprentice Scholar Robe",
    category: "outfit",
    rarity: "common",
    cost: 0,
    currency: "coins",
    description: "Comfortable and ready for study.",
    visualTag: "outfit_novice",
  },
  {
    id: "outfit_rock_leather",
    name: "Rockstar Studded Leather Jacket",
    category: "outfit",
    rarity: "rare",
    cost: 320,
    currency: "coins",
    description: "Studded with chrome buttons representing prime numbers.",
    visualTag: "outfit_rock_leather",
  },
  {
    id: "outfit_paladin_armor",
    name: "Golden Paladin Plate Armor",
    category: "outfit",
    rarity: "epic",
    cost: 650,
    currency: "coins",
    description: "Shields against the most daunting division questions.",
    visualTag: "outfit_paladin_armor",
    glowColor: "#eab308",
  },
  {
    id: "outfit_cyber_suit",
    name: "Neon Cyber Mesh Suit",
    category: "outfit",
    rarity: "mythic",
    cost: 65,
    currency: "gems",
    description: "Interlaced with quantum nano-tubes and dynamic HUD.",
    visualTag: "outfit_cyber_suit",
    glowColor: "#3b82f6",
    perk: "+15% Coin & XP Bonus",
  },

  // WEAPONS & INSTRUMENTS
  {
    id: "weapon_wooden_ruler",
    name: "Standard 30cm Oak Ruler",
    category: "weapon",
    rarity: "common",
    cost: 0,
    currency: "coins",
    description: "Trusty school desk essential.",
    visualTag: "weapon_ruler",
  },
  {
    id: "weapon_thunder_guitar",
    name: "Thunderbolt Flying-V Guitar",
    category: "weapon",
    rarity: "epic",
    cost: 500,
    currency: "coins",
    description: "Shreds times table solos that shake the arena!",
    visualTag: "weapon_thunder_guitar",
    glowColor: "#e11d48",
  },
  {
    id: "weapon_excalibur_compass",
    name: "Excalibur Geometry Compass",
    category: "weapon",
    rarity: "legendary",
    cost: 950,
    currency: "coins",
    description: "Draws circles of pure arithmetic destruction.",
    visualTag: "weapon_excalibur_compass",
    glowColor: "#38bdf8",
  },
  {
    id: "weapon_flaming_wand",
    name: "Dragon Fire Wand",
    category: "weapon",
    rarity: "rare",
    cost: 300,
    currency: "coins",
    description: "Casts quick-recall fireballs at boss monsters.",
    visualTag: "weapon_flaming_wand",
    glowColor: "#f97316",
  },
  {
    id: "weapon_cosmic_abacus",
    name: "Cosmic Nebula Abacus",
    category: "weapon",
    rarity: "mythic",
    cost: 80,
    currency: "gems",
    description: "Manipulates spacetime equations with glowing beads.",
    visualTag: "weapon_cosmic_abacus",
    glowColor: "#a855f7",
    perk: "+20% Boss Damage",
  },

  // SHIELDS
  {
    id: "shield_knight",
    name: "Times Table Crest Shield",
    category: "shield",
    rarity: "common",
    cost: 120,
    currency: "coins",
    description: "Bearing the sacred 7x8=56 insignia.",
    visualTag: "shield_knight",
  },
  {
    id: "shield_golden_aegis",
    name: "Aegis of the 12s",
    category: "shield",
    rarity: "epic",
    cost: 400,
    currency: "coins",
    description: "Guards against time-out penalties in Boss Raid.",
    visualTag: "shield_golden_aegis",
    glowColor: "#eab308",
  },

  // AURAS & EFFECTS
  {
    id: "aura_lightning",
    name: "Electric Thunder Sparks",
    category: "aura",
    rarity: "rare",
    cost: 350,
    currency: "coins",
    description: "Crackles around you as your recall speed quickens.",
    visualTag: "aura_lightning",
    glowColor: "#eab308",
  },
  {
    id: "aura_rainbow_stars",
    name: "Prismatic Stardust Cascade",
    category: "aura",
    rarity: "legendary",
    cost: 35,
    currency: "gems",
    description: "Rainbow stardust leaves a trail when answering questions.",
    visualTag: "aura_rainbow_stars",
    glowColor: "#ec4899",
  },
  {
    id: "aura_math_runes",
    name: "Floating Golden Equation Runes",
    category: "aura",
    rarity: "mythic",
    cost: 70,
    currency: "gems",
    description: "Glowing equations orbit your champion continuously.",
    visualTag: "aura_math_runes",
    glowColor: "#38bdf8",
  },

  // PETS & FAMILIARS
  {
    id: "pet_calcul_owl",
    name: "Archimedes the Calcul-Owl",
    category: "pet",
    rarity: "rare",
    cost: 420,
    currency: "coins",
    description: "Hoo-hoo! Whispers encouragement when tackling tricky 9s.",
    visualTag: "pet_owl",
  },
  {
    id: "pet_byte_dragon",
    name: "Byte the Pixel Dragon",
    category: "pet",
    rarity: "epic",
    cost: 750,
    currency: "coins",
    description: "Breathes sparks whenever you hit a 5-streak combo!",
    visualTag: "pet_dragon",
    glowColor: "#10b981",
  },
  {
    id: "pet_griffin_gold",
    name: "Solar Griffin Companion",
    category: "pet",
    rarity: "legendary",
    cost: 50,
    currency: "gems",
    description: "Majestic mythical creature soaring alongside your hero.",
    visualTag: "pet_griffin",
    glowColor: "#f59e0b",
  },

  // TITLES
  {
    id: "title_table_conqueror",
    name: "The Table Conqueror",
    category: "title",
    rarity: "rare",
    cost: 150,
    currency: "coins",
    description: "Bestowed upon warriors who master up to 12x12.",
    visualTag: "title",
  },
  {
    id: "title_lightning_fingers",
    name: "Lightning Fingers",
    category: "title",
    rarity: "epic",
    cost: 300,
    currency: "coins",
    description: "For math speedsters averaging under 1.5 seconds.",
    visualTag: "title",
  },
  {
    id: "title_grand_archmage",
    name: "Grand Archmage of Arithmetic",
    category: "title",
    rarity: "mythic",
    cost: 45,
    currency: "gems",
    description: "The ultimate title in the realm of numbers.",
    visualTag: "title",
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: "quest_daily_login",
    title: "Daily Arena Check-In",
    desc: "Log in today to claim your daily training stipend.",
    target: 1,
    current: 1,
    rewardCoins: 50,
    rewardGems: 2,
    completed: true,
    claimed: false,
    icon: "📅",
  },
  {
    id: "quest_answer_25",
    title: "Rapid Fact Storm",
    desc: "Answer 25 times table questions correctly in any game mode.",
    target: 25,
    current: 0,
    rewardCoins: 120,
    rewardGems: 5,
    completed: false,
    claimed: false,
    icon: "⚡",
  },
  {
    id: "quest_play_mtc",
    title: "National MTC Trial",
    desc: "Complete 1 full Year 4 MTC Simulation round.",
    target: 1,
    current: 0,
    rewardCoins: 150,
    rewardGems: 8,
    completed: false,
    claimed: false,
    icon: "📜",
  },
  {
    id: "quest_boss_battle",
    title: "Dungeon Boss Strike",
    desc: "Deal 100+ damage to a Dungeon Boss using quick math spells.",
    target: 100,
    current: 0,
    rewardCoins: 200,
    rewardGems: 10,
    completed: false,
    claimed: false,
    icon: "🐉",
  },
];
